### ISSUE TITLE
Core dump when repeatedly `unmailboxes` and `mailboxes = [something]`

### ISSUE THREAD

**Issue by Ron89** [karelzak/mutt-kz#125] opened 2016-04-05 15:31 UTC
As title suggests,
Simply repeatedly use command
```
    unmailboxes
    mailboxes =INBOX =...
```
And soon mutt will crash with error message
```
    [1]     19030 segmentation fault (core dumped)  mutt
```
and exit state `139`.

I suspect there be mis-management for memory allocation in function `unmailboxes`.

**Comment by shioyama** [comment] 2016-04-06 13:04
This is an issue with the version of the sidebar that is used in mutt-kz. I'd suggest giving [neomutt](http://www.neomutt.org/) a try intead, it has mutt-kz changes incorporated in it and also has the fixed sidebar. I created an [aur package for it](https://aur.archlinux.org/packages/neomutt/) just now which should be a near-drop-in replacement for mutt-kz.

**Comment by shioyama** [comment] 2016-04-06 13:07
p.s. see #124

**Comment by Ron89** [comment] 2016-04-06 13:10
Noted, will try. Thanks~

**Comment by karelzak** [comment] 2016-04-07 07:55
On Wed, Apr 06, 2016 at 06:04:52AM -0700, Chris Salzberg wrote:
> This is an issue with the version of the sidebar that is used in
> mutt-kz. 

mutt-kz version 1.6.0.1 is based on sidebar from neomutt

> I'd suggest giving [neomutt](http://www.neomutt.org/) a try
> intead, it has mutt-kz changes incorporated in it and also has the
> fixed sidebar. I created an [aur package for
> it](https://aur.archlinux.org/packages/neomutt/) just now which
> should be a near-drop-in replacement for mutt-kz.

right now there is no difference between neo-mutt and mutt-kz. (Well,
neo-mutt contains some another extensions).

The goal of the neo-mutt project is keep up to date unofficial mutt
changes (and if possible then push to the mutt upstream). The goal of
mutt-kz is to develop and maintain notmuch support. The plan is to
collaborate to keep things synced.

    Karel

-- 
 Karel Zak  <kzak@redhat.com>
 http://karelzak.blogspot.com

**Comment by Ron89** [comment] 2016-04-08 02:22
I haven't seen the code relating sidebar. But neovim's sidebar is working pretty stable even when I frequently `<change-folder>`. Could you check on this if you have the time?

**Comment by flatcap** [comment] 2016-04-09 17:35
@shioyama 
Thanks for creating the Arch package.  I have some questions...

- What can I do to NeoMutt to help you?
- Are you going to continue maintaining the package?
- I looked at the package and it seems to pull directly from git.  How much work would it be to only use "official" releases (those date-tagged)?
- Would a floating "latest-release" tag be useful?
- Do you mind if I name you on the NeoMutt website and link to the package? (You can be the first entry on the Packagers page).
- How can we get more Arch users using NeoMutt?

Cheers,
    Rich \<rich@flatcap.org\>

**Comment by shioyama** [comment] 2016-04-20 14:29
@flatcap About the package, I'll continue maintaining it as long as I'm using it, unless someone else wants to (happy to hand it over to anyone else).

> I looked at the package and it seems to pull directly from git. How much work would it be to only use "official" releases (those date-tagged)?

I just wanted something quick so based it off git but really it should probably be named `neomutt-git` and another package `neomutt` should only have official releases. I'm happy to swap those around.

> Would a floating "latest-release" tag be useful?

I don't think that's necessary, the package would anyway need to be updated manually if it's not simply pulling from the `neomutt` branch.

> Do you mind if I name you on the NeoMutt website and link to the package?

Not at all! But again, I did very little, just took the existing mutt-kz-git package and tweaked it a bit.

> How can we get more Arch users using NeoMutt?

Make Mutt great and people will use it :smile: I think there's a lot of work going on in parallel so I quite like your attempt to pull things together into one place.

**Comment by karelzak** [comment] 2016-04-25 09:19
I guess the issue is already fixed, close?

**Comment by flatcap** [comment] 2016-04-25 10:48
You created a fix for this.  Then I changed sidebar a bit to get rid of some dodgy code.
You've already merged the improved version.

Yes, close this issue.  I'm confident the bug is fixed.

**Closed** 2016-04-30 00:17 UTC
